In [1]:
import pandas as pd

# Load your file with the correct path syntax
df = pd.read_csv("C:/Users/shilp/Downloads/Ecommerce_Consumer_Behavior_Analysis_Data.csv")

# Display the data table directly below
df

,Customer_ID,Age,Age-Group,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,19-29,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,...,7,NaN,Tablet,Credit Card,03-01-2024,True,False,Need-based,No Preference,2
1,29-392-9296,49,30-49,Male,High,Married,High School,High,Huocheng,Food & Beverages,...,5,High,Tablet,PayPal,04-01-2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,19-29,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,...,7,Low,Smartphone,Debit Card,05-01-2024,True,True,Impulsive,No Preference,3
3,48-980-6078,29,19-29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,...,1,NaN,Smartphone,Other,06-01-2024,True,True,Need-based,Express,10
4,91-170-9072,33,70+,Female,Middle,Widowed,High School,Middle,Nara,Furniture,...,10,NaN,Smartphone,Debit Card,07-01-2024,False,False,Wants-based,No Preference,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20-562-2569,44,70+,Female,High,Divorced,Bachelor's,High,Aramayuan,Mobile Accessories,...,4,NaN,Tablet,PayPal,24-09-2026,True,False,Need-based,Standard,5
996,41-366-4205,50,30-49,Female,High,Single,High School,Middle,Paquera,Gardening & Outdoors,...,6,Low,Tablet,Cash,25-09-2026,True,False,Wants-based,No Preference,9
997,77-241-7621,26,19-29,Male,High,Married,Bachelor's,High,Warudoyong,Food & Beverages,...,6,High,Desktop,Credit Card,26-09-2026,True,True,Wants-based,Express,9
998,53-091-2176,21,19-29,Female,High,Widowed,Bachelor's,Middle,Béziers,Baby Products,...,5,Medium,Desktop,Cash,27-09-2026,True,True,Impulsive,Standard,8
999,48-203-9118,21,19-29,Female,Middle,Single,High School,High,Dongzhou,Health Care,...,10,Low,Tablet,Other,28-09-2026,False,False,Planned,Express,2

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
pd.set_option('display.max_columns',None)
df

,Customer_ID,Age,Age-Group,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,Frequency_of_Purchase,Purchase_Channel,Brand_Loyalty,Product_Rating,Time_Spent_on_Product_Research(hours),Social_Media_Influence,Discount_Sensitivity,Return_Rate,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,19-29,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,333.80,4,Mixed,5,5,2.00,NaN,Somewhat Sensitive,1,7,NaN,Tablet,Credit Card,03-01-2024,True,False,Need-based,No Preference,2
1,29-392-9296,49,30-49,Male,High,Married,High School,High,Huocheng,Food & Beverages,222.22,11,In-Store,3,1,2.00,Medium,Not Sensitive,1,5,High,Tablet,PayPal,04-01-2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,19-29,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,426.22,2,Mixed,5,5,0.30,Low,Not Sensitive,1,7,Low,Smartphone,Debit Card,05-01-2024,True,True,Impulsive,No Preference,3
3,48-980-6078,29,19-29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,101.31,6,Mixed,3,1,1.00,High,Somewhat Sensitive,0,1,NaN,Smartphone,Other,06-01-2024,True,True,Need-based,Express,10
4,91-170-9072,33,70+,Female,Middle,Widowed,High School,Middle,Nara,Furniture,211.70,6,Mixed,3,4,0.00,Medium,Not Sensitive,2,10,NaN,Smartphone,Debit Card,07-01-2024,False,False,Wants-based,No Preference,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20-562-2569,44,70+,Female,High,Divorced,Bachelor's,High,Aramayuan,Mobile Accessories,463.67,5,Online,2,4,0.30,High,Not Sensitive,2,4,NaN,Tablet,PayPal,24-09-2026,True,False,Need-based,Standard,5
996,41-366-4205,50,30-49,Female,High,Single,High School,Middle,Paquera,Gardening & Outdoors,69.78,9,Mixed,4,3,2.00,Low,Very Sensitive,0,6,Low,Tablet,Cash,25-09-2026,True,False,Wants-based,No Preference,9
997,77-241-7621,26,19-29,Male,High,Married,Bachelor's,High,Warudoyong,Food & Beverages,453.37,10,Mixed,1,1,2.00,Low,Very Sensitive,0,6,High,Desktop,Credit Card,26-09-2026,True,True,Wants-based,Express,9
998,53-091-2176,21,19-29,Female,High,Widowed,Bachelor's,Middle,Béziers,Baby Products,106.15,12,In-Store,4,4,0.30,Low,Somewhat Sensitive,0,5,Medium,Desktop,Cash,27-09-2026,True,True,Impulsive,Standard,8
999,48-203-9118,21,19-29,Female,Middle,Single,High School,High,Dongzhou,Health Care,378.47,6,Online,5,2,0.33,Medium,Not Sensitive,1,10,Low,Tablet,Other,28-09-2026,False,False,Planned,Express,2